### ISSUE TITLE
Fix acme challenge to work always instead of just sometimes.

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/terraform-google-astronomer-gcp#22]
the problem is similar to this one https://community.letsencrypt.org/t/dns-servers-used-by-letsencrypt-for-challenges/32127

I think maybe if we use this data source and use the name_servers attribute as an input to the 'recursive_nameservers' argument on the acme_certificate resource, we may have better luck
https://www.terraform.io/docs/providers/google/d/dns_managed_zone.html

**Comment by kaxil** [comment]
https://github.com/terraform-providers/terraform-provider-acme/issues/71

**Comment by sjmiller609** [comment]
I have increased the polling interval, this may make it less probable to fail, but probably not fix it.

**Comment by sjmiller609** [comment]
It may have worked, we will see. the first run worked https://cloud.drone.io/astronomer/terraform-google-astronomer-gcp/59

**Comment by sjmiller609** [comment]
This problem has not recurred for a while, so I'm going to close this story
