### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/terraform-google-astronomer-gcp#8]
1 and 2 may run simultaneously

1)
- terraform apply to deploy from scratch
- run python system testing in the form of python unit tests. For this issue, don't go overboard, just keep it simple like a check that the database and the GKE cluster exist using boto3, use testinfra to check that tinyproxy is running on port 8888 of the bastion. This just serves as an outline for adding additional tests. This way other developers can reference these examples when they add more tests. eventually we will want to add comprehensive testing, especially around security groups and networks, but not for the sake of this issue.
- terraform destroy

2)

EDIT, new plan:

- terraform apply the previous, working version (most recent version from terraform registry)
- terraform apply
- require a major version update on this module if any resources (or a list of important resources?) have interrupting updates.
- run system tests
- terraform destroy

I also think we should use behave testing for this, same as this issue https://github.com/astronomer/terraform-kubernetes-astronomer/issues/5

The below is a very rough outline

Given GCP credentials in the CI account
When terraform is applied
Then python system testing passes
When terraform is destroyed

Given GCP credentials in the CI account
When the most recent version is applied
And terraform is applied
And if there was an interrupt on important resources, then require a major version upgrade
When terraform is destroyed

**Comment by sjmiller609** [comment]
@kaxil this one is pretty much the same as the one on AWS

**Comment by sjmiller609** [comment]
@kaxil I updated this one similar to the edit in AWS you suggested

**Comment by kaxil** [comment]
Agree 👍

**Comment by sjmiller609** [comment]
We now have CI testing, we can create additional issues for additional features.
